### ISSUE TITLE
missing node-lemmer in npm install

### ISSUE THREAD

**Issue by rayearl** [silentrob/superscriptjs.com#6] opened 2015-03-09 13:30 UTC
error message comes up from superscript install log on ubuntu 14.04

**Comment by silentrob** [comment] 2015-03-09 19:00
What version of Node are you using? Can you provide a little more detail on the message?

**Comment by rayearl** [comment] 2015-03-10 01:32
Node version: v0.10.25

Here is last segment of log file:

643 http 304 https://registry.npmjs.org/mkdirp
644 silly registry.get cb [ 304,
644 silly registry.get   { date: 'Mon, 09 Mar 2015 03:29:46 GMT',
644 silly registry.get     server: 'Apache',
644 silly registry.get     via: '1.1 varnish',
644 silly registry.get     'last-modified': 'Mon, 09 Mar 2015 03:29:12 GMT',
644 silly registry.get     'cache-control': 'max-age=60',
644 silly registry.get     etag: '"6VM3USX2JE4Z97IZCV8532A6V"',
644 silly registry.get     age: '45',
644 silly registry.get     'x-served-by': 'cache-sjc3121-SJC',
644 silly registry.get     'x-cache': 'HIT',
644 silly registry.get     'x-cache-hits': '2',
644 silly registry.get     'x-timer': 'S1425871786.435078,VS0,VE0',
644 silly registry.get     vary: 'Accept',
644 silly registry.get     'content-length': '0',
644 silly registry.get     'keep-alive': 'timeout=10, max=48',
644 silly registry.get     connection: 'Keep-Alive' } ]
645 verbose etag mkdirp from cache
646 silly lockFile 4086e98d-t-github-com-grachev-node-lemmer git://github.com/grachev/node-lemmer
647 silly lockFile 4086e98d-t-github-com-grachev-node-lemmer git://github.com/grachev/node-lemmer
648 info maybeGithub Attempting grachev/node-lemmer from git+ssh://git@github.com:grachev/node-lemmer
649 silly lockFile 822817be-t-github-com-grachev-node-lemmer git+ssh://git@github.com:grachev/node-lemmer
650 verbose lock git+ssh://git@github.com:grachev/node-lemmer /home/ubuntu/.npm/822817be-t-github-com-grachev-node-lemmer.lock
651 silly addNameRange number 2 { name: 'mkdirp', range: '>=0.5.0-0 <0.6.0-0', hasData: true }
652 silly addNameRange versions [ 'mkdirp',
652 silly addNameRange   [ '0.0.1',
652 silly addNameRange     '0.0.2',
652 silly addNameRange     '0.0.3',
652 silly addNameRange     '0.0.4',
652 silly addNameRange     '0.0.5',
652 silly addNameRange     '0.0.6',
652 silly addNameRange     '0.0.7',
652 silly addNameRange     '0.1.0',
652 silly addNameRange     '0.2.0',
652 silly addNameRange     '0.2.1',
652 silly addNameRange     '0.2.2',
652 silly addNameRange     '0.3.0',
652 silly addNameRange     '0.3.1',
652 silly addNameRange     '0.3.2',
652 silly addNameRange     '0.3.3',
652 silly addNameRange     '0.3.4',
652 silly addNameRange     '0.3.5',
652 silly addNameRange     '0.4.0',
652 silly addNameRange     '0.4.1',
652 silly addNameRange     '0.4.2',
652 silly addNameRange     '0.5.0' ] ]
653 verbose addNamed [ 'mkdirp', '0.5.0' ]
654 verbose addNamed [ '0.5.0', '0.5.0' ]
655 silly lockFile bf9ae38d-mkdirp-0-5-0 mkdirp@0.5.0
656 verbose lock mkdirp@0.5.0 /home/ubuntu/.npm/bf9ae38d-mkdirp-0-5-0.lock
657 silly lockFile 5ac0f0c2-WNdb-3-1-1 WNdb@3.1.1
658 silly lockFile 5ac0f0c2-WNdb-3-1-1 WNdb@3.1.1
659 verbose addRemoteGit [ 'git@github.com:grachev/node-lemmer', 'master' ]
660 silly lockFile f32d4ac5-WNdb-3-1-1 WNdb@~3.1.1
661 silly lockFile f32d4ac5-WNdb-3-1-1 WNdb@~3.1.1
662 silly lockFile 6fe5105c-t-github-com-grachev-node-lemmer git@github.com:grachev/node-lemmer
663 silly lockFile 959027d8-node-lemmer-grachev-node-lemmer node-lemmer@grachev/node-lemmer
664 silly lockFile 959027d8-node-lemmer-grachev-node-lemmer node-lemmer@grachev/node-lemmer
665 verbose about to build /usr/local/lib/node_modules/superscript
666 info /usr/local/lib/node_modules/superscript unbuild
667 info preuninstall superscript@0.6.7
668 info uninstall superscript@0.6.7
669 verbose true,/usr/local/lib/node_modules,/usr/local/lib/node_modules unbuild superscript@0.6.7
670 verbose /usr/local/bin,[object Object] binRoot
671 silly lockFile bf9ae38d-mkdirp-0-5-0 mkdirp@0.5.0
672 silly lockFile bf9ae38d-mkdirp-0-5-0 mkdirp@0.5.0
673 silly lockFile 0879e7d7-mkdirp-0-5-0 mkdirp@^0.5.0
674 silly lockFile 0879e7d7-mkdirp-0-5-0 mkdirp@^0.5.0
675 info postuninstall superscript@0.6.7
676 error 404 'node-lemmer' is not in the npm registry.
676 error 404 You should bug the author to publish it
676 error 404
676 error 404 Maybe try 'npm search lemmer'
676 error 404
676 error 404 Note that you can also install from a
676 error 404 tarball, folder, or http url, or git url.
677 error System Linux 3.13.0-44-generic
678 error command "/usr/bin/nodejs" "/usr/bin/npm" "install" "superscript" "-g"
679 error cwd /
680 error node -v v0.10.25
681 error npm -v 1.3.10
682 error code E404
683 verbose exit [ 1, true ]

**Comment by silentrob** [comment] 2015-03-10 01:39
Thanks.

**Comment by silentrob** [comment] 2015-03-10 03:56
I believe the issue is related to your version of NPM - https://github.com/npm/npm/blob/master/CHANGELOG.md#v140-2014-02-12 
The repo in question is being pulled in from github user/repo and not NPM registry.

I'm currently using 1.4.28 and unable to reproduce the problem. I will bump to 2.x over the next few weeks and re-test it.

**Comment by silentrob** [comment] 2015-03-10 03:58
I'm going to close this issue, if it still persists, please open on http://github.com/silentrob/superscript/issues

**Closed by silentrob** 2015-03-10 03:58 UTC
